### ISSUE TITLE
UserInfo={NSLocalizedDescription=remote notifications are not supported in the simulator}

### ISSUE THREAD

**Issue by siddhant3030** [myteeNatanwit/pushTest#1]
Hey.

Apple Swift version 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51)
Target: x86_64-apple-darwin19.4.0

I'm trying to do the same thing in one of swift code but I'm getting this error and I'm not sure what it's related to. 

`Permission granted: true
Failed to register for remote notifications with error: Error Domain=NSCocoaErrorDomain Code=3010 "remote notifications are not supported in the simulator" UserInfo={NSLocalizedDescription=remote notifications are not supported in the simulator}`

Here I'm getting permission granted true

But not able to fetch the token. Can you help me understand what is it I'm doing wrong here?

**Comment by myteeNatanwit** [comment]
my guess is you didnt run it on a real phone.

Michael T
0400121882
decten76@gmail.com
intcloud.mobi/appstore

**Comment by siddhant3030** [comment]
I was thinking that it has to do something with a version of the ios app. But turns out it will not work. Thanks for your reply. 
I will close this issue
